### PR TITLE
Merge issue-15

### PR DESCRIPTION
**Pull request by kemartin2015**

### CODE REVIEW

**Comment by a-berish** [comment]
I tested it, and it's working just fine! 😃

**Review by a-berish — APPROVED** [review]
I tested it and it's working just fine for me!

**Review by helrond — APPROVED** [review]
This all looks right to me

**Review by helrond — CHANGES_REQUESTED** [review]
We need to update the README too (which currently says this library is written for Python 2.7)

**Review by bonniegee — CHANGES_REQUESTED** [review]
In order to keep this consistent (and align with Python best practices), we may want to use spaces and not tabs for indentation.

**Comment by a-berish** [comment]
> In order to keep this consistent (and align with Python best practices), we may want to use spaces and not tabs for indentation.

Could we merge this after addressing Hillel's comment about the README and _then_ run the linter/syntax formater since we're working on #18 this week?

**Review by bonniegee — APPROVED** [review]

**Review by daremiyo — APPROVED** [review]

**Review by helrond — APPROVED** [review]

**Pull request merged**
