### PR TITLE
Check `notes` for `scopecontent` and `accessrestrict`

### PR DESCRIPTION
**Pull request by bonniegee**
Once I added a fixture to test this, I realized this was a bit more complicated than I had initially commented in the issue. I had to use the `anyOf` keyword in combination with `minContains`. But in order to use `minContains`, I needed to use a validator that was newer than Draft 7--so I've updated the validator to use the most recent draft.

(I should note that there's a possibility here--that I haven't tested--that a resource with, e.g., two scope and contents notes and no access restrictions notes would be valid using this schema.)

### CODE REVIEW

**Comment by helrond** [comment]
I just tested it out and a resource with two `scopecontent` notes and no `accessrestrict` is valid using this schema.

**Comment by helrond** [comment]
@bonniegee I saw [this](https://stackoverflow.com/questions/59176042/validate-array-json-contains-several-unordered-objects-using-json-schema) example and replicated it - I _think_ it works.

**Comment by bonniegee** [comment]
I can't get it to work--I printed the errors from testing the valid fixture:

> tests/test_validator.py [{'jsonmodel_type': 'note_multipart', 'persistent_id': 'bf2011f3353f37f389577d36cd942721', 'type': 'accessrestrict', 'rights_restriction': {'local_access_restriction_type': []}, 'subnotes': [{'jsonmodel_type': 'note_text', 'content': 'Open for research with select materials restricted as noted. Brittle or damaged items are available at the discretion of RAC.', 'publish': True}], 'publish': True}, {'jsonmodel_type': 'note_multipart', 'persistent_id': 'b4ad37dbd0891b871c8fe5d3e969f487', 'type': 'userestrict', 'rights_restriction': {'local_access_restriction_type': []}, 'subnotes': [{'jsonmodel_type': 'note_text', 'content': 'RAC holds legal title. The Henry Luce Foundation retains all applicable intellectual property rights in so far as it holds them.', 'publish': True}], 'publish': True}, {'jsonmodel_type': 'note_multipart', 'persistent_id': 'a0fb232b40ebc33ff21f51fc5fa71017', 'type': 'scopecontent', 'subnotes': [{'jsonmodel_type': 'note_text', 'content': 'The Henry Luce Foundation was established by Henry R. Luce in 1936. As a New York-based nonprofit organization, the Luce Foundation awards grants in American Art, Asian studies, Higher Education, Theology, and supports the Clare Boothe Luce Program for women in science, mathematics, and engineering.', 'publish': True}], 'publish': True}] does not contain items matching the given schema

**Comment by bonniegee** [comment]
Following up to say that I had missed the commit, and so I had tried implementing this myself--and did it incorrectly. (I flipped how `allOf` and `contains` are nested.) So this solution does work!

**Comment by helrond** [comment]
Looking at this a bit more after the haze of last week has cleared, I'm wondering if the `minContains` is necessary/doing anything in this context? It may be possible to get rid of that key/value pair in the two blocks.

**Comment by bonniegee** [comment]
@helrond Yeah that sounds right--from my understanding of the documentation, `contains` without `minContains` is the same as setting `minContains` to `1`.

If we're getting rid of `minContains`, that means we technically could revert back to Draft 7--but we probably want to be on the most recent version of the validator anyway?

**Comment by bonniegee** [comment]
As discussed, I removed `minContains`. I also added a fixture with two scope and contents notes and no access restriction, and a fixture with neither a scope and contents note nor an access restriction.

I also changed how we're getting the fixtures in the tests--so it'll be easier to drop valid and invalid fixtures in and out as we build out functionality.

**Review by helrond — APPROVED** [review]

**Comment by bonniegee** [comment]
I should note that this also fixes #50

**Review by daremiyo — APPROVED** [review]

**Review by a-berish — APPROVED** [review]

**Review by kemartin2015 — APPROVED** [review]

**Pull request merged**
