### PR TITLE
Adds command-line flags using argparse

### LINKED ISSUE #25: Pass command-line flags rather than asking for user input
DACSSpace currently requires user input, which means that the script cannot be run from a cron job and must always be triggered by a human. Using `argparse`, add command-line flags for necessary arguments. 

Current flags:
- include unpublished?
- filter for specific resource ID

### PR DESCRIPTION
**Pull request by kemartin2015**
Fixes #25

I’m getting a SystemExit error when I run tox and I’m not sure how to resolve it. 

I also want to make sure I’m approaching the Boolean arguments in the right way.  As I’m understanding this, to specify invalid_only and published_only, you would need to invoke those flags in the command line. If you don’t, then you would get back all resources and both valid and invalid results? 

Also didn’t want to mention Hillel’s comment from #51 where there is more work to be done: “The idea would be that users would only be able to submit either a schema identifier or a filepath, and that validation would be handled in argparse using [mutual exclusion](https://docs.python.org/3/library/argparse.html#mutual-exclusion).”

### CODE REVIEW

**Comment by helrond** [comment]
@kemartin2015 I think you might need to wrap the last line in an if statement:
```
if __name__ == '__main__':
    DACSspace().run(args.published_only, args.invalid_only)
```

Explanation for that [here](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

**Comment by helrond** [comment]
Ah, I think you need to put all of that argparse stuff inside that `if` statement...

**Comment by helrond** [comment]
I think you're passing those booleans correctly, but I wonder if the second one should have a `store_true` action as well?

Also, I think there's additional work we'll need to do to make this truly executable on the command line. Right now if you try to run `python dacsspace.py` you'll get some import errors. I'm not even sure right now what needs to be done, so maybe that's a separate issue.

**Comment by bonniegee** [comment]
I did some quick Googling, and it looks like if we want to use `__main__`, we can't use the current flat file structure. `dacsspace.py` would need to be at the same level as the `dacsspace` directory. However, that means we would also need to change the current `dacsspace/__init__.py`, so +1 to this maybe being a separate issue.

**Comment by kemartin2015** [comment]
I changed the file structure, removed the code from `dacsspace/__init__.py`, and adjusted the dacsspace imports and now the tests are passing and I'm no longer getting import errors when I run `python dacsspace.py.` I'm getting some positional argument errors now though when I run `python dacsspace.py.`. For example, `TypeError: Validator.__init__() takes 1 positional argument but 3 were given.` Will that potentially be resolved by changes that have been implemented in other files in the time since this PR was opened?

**Comment by helrond** [comment]
@kemartin I think you need to merge the most recent version of `base` into your local `issue-25` branch because you don't have all of the recent changes that have been merged to `base` since you branched off of it.

**Comment by helrond** [comment]
I also think there may be scope slippage happening with this issue that we should talk about on Monday. To me, the issue this is addressing reads like "implement argparse" but it doesn't really say anything about being able to run the script on the command line (which I think is a function of me writing a less-than-ideal issue) so it might be good to touch base on when this PR can be merged, and what work would need to be added to a new issue.

**Review by helrond — APPROVED** [review]

**Review by daremiyo — APPROVED** [review]

**Review by a-berish — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
